services:
  sql: 
    image: mcr.microsoft.com/azure-sql-edge # Docker version of SQL & lightweight version of SQL Server.
    container_name: sql
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433" #internalport-externalport


      #internalport: whatever running internally.
      #externalport: access to the services.